### ISSUE TITLE
Feature request: Modifier key to open the result as "i'm feeling lucky"

### ISSUE THREAD

**Issue by snowliondev** [alfredapp/google-suggest-workflow#1]
Would be very useful if you want to jump straight to the top listing of a suggested term.

**Comment by vitorgalvao** [comment]
That’s a nice idea, but unfortunately it doesn’t really work because Google [somewhat broke](https://superuser.com/questions/1496083/google-feeling-lucky-url-causing-redirect-notice) that solution [years ago](https://support.google.com/websearch/thread/15794018).

Now if you try to do it directly (not from their homepage) it sends you to a redirect page where you have to click a link anyway, which kind of defeats the purpose.

**Comment by snowliondev** [comment]
I found the solution is to add a custom search engine and add "https://duckduckgo.com/?q=!ducky%20{query}". This still works to go straight to the site.
