### ISSUE TITLE
it would be great, if the google suggest workflow could be added in the 'Fallbacks'

### ISSUE THREAD

**Issue by andyandhope** [alfredapp/google-suggest-workflow#2]
### Feature details

it would be great, if the google suggest workflow could be added in the 'Fallbacks', 
as no any 'keyword' is needed, the google suggetions are showing by default.

**Comment by vitorgalvao** [comment]
That is not possible in the way you ask. Fallbacks never present their results immediately, you always have to <kbd>↩</kbd> on the entry. With good reason: with your suggestion, *everything* you typed would be sent to Google as a search, which not only would be bad for privacy but might get your IP banned from any search due to sending too many all the time.

No reason to not add it as a regular fallback, though. I’ll do that today and close the issue when the update is live.
